kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    name: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: "django-server"
  clusterIP: 192.168.3.111
  type: LoadBalancer
