kind: PersistentVolume
apiVersion: v1
metadata:
  name: master-local-postgres-pv
  labels:
    type: master-local-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
