apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: postgres
  name: postgres-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
          - name: POSTGRES_USER
            value: 'a_user'
          - name: POSTGRES_PASSWORD
            value: 'a_password'
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /data/db
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: master-local-postgres-pvc
