kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    name: angular
  ports:
  - protocol: TCP
    nodePort: 30000
    port: 80
    targetPort: "http-server"
  type: LoadBalancer
