kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    name: django
  ports:
  - protocol: TCP
    nodePort: 31000
    port: 9000
    targetPort: "http-server"
  type: LoadBalancer
