kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    name: django
  ports:
  - protocol: TCP
     nodePort: 31001
     port: 9000
     targetPort: "django-server"
  type: LoadBalancer