piVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: 'dnav'
    # foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook.prod
          servicePort: 3000
  - host: 'qa.dnav'
    http:
    paths:
      - path: /
        backend:
          serviceName: guestbook.qa
          servicePort: 3000

