kind: PersistentVolume
apiVersion: v1
metadata:
  name: master-local-postgres
  labels:
    type: master-local-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
