kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx-ssl-proxy
  labels:
    name: nginx
    role: ssl-proxy
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
    spec:
      containers:
      - name: nginx-ssl-proxy
        image: matthewpbyrne/nginx-ssl-proxy
        command:
        - /bin/bash
        - /usr/bin/start.sh
        env:
        - name: ENABLE_SSL
          value: 'false'
        - name: ENABLE_BASIC_AUTH
          value: 'false'
        - name: TARGET_SERVICE
          value: 10.84.107.169
        ports:
        - name: ssl-proxy-http
          containerPort: 80
        - name: ssl-proxy-https
          containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: ssl-proxy-secret
